name = "workers-tunnel"
main = "build/worker/shim.mjs"
compatibility_date = "2024-01-03"

[build]
command = "cargo install -q worker-build && worker-build --release"

[vars]
USER_ID = "49e5833b-0c62-4d09-bb17-3d1e38d0ec55"
